//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Specialized;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using AutoVFA.Misc;

namespace AutoVFA {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class AppSettings : ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public StringCollection SamplePaths {
            get {
                return ((StringCollection)(this["SamplePaths"]));
            }
            set {
                this["SamplePaths"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public StringCollection StandardPaths {
            get {
                return ((StringCollection)(this["StandardPaths"]));
            }
            set {
                this["StandardPaths"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public CVThreshold CVThreshold {
            get {
                return ((CVThreshold)(this["CVThreshold"]));
            }
            set {
                this["CVThreshold"] = value;
            }
        }
    }
}
